### ISSUE TITLE
Version unpack exception

### ISSUE THREAD

**Issue by clusby** [jborean93/ntlm-auth#10]
Hi,

When using via requests-ntlm 2.17.3 (which uses the default ntlm_compatibility=3), I get an exception with my proxy:

```
  File "C:\...\lib\site-packages\ntlm_auth\messages.py", line 144, in __init__
    self.version = struct.unpack("<q", msg2[48:56])[0]
struct.error: unpack requires a string argument of length 8
```

I checked len(msg2) == 48 (which would be why unpack fails)

If I explicitly set the ntlm_compatibility = 0, then it correctly authenticates. 

Any tips? Is our ntlm proxy doing something unexpected?

Thanks

**Comment by jborean93** [comment]
That's weird, those values should be populated if the flags are set. Are you able to send through the 1st and 2nd messages in the base64 encoded form. I'll have a look at them and try and determine what their structure is.

Do you know if your proxy supports NTLMv2? The reason why setting ntlm_compatibility to a lower version is that it uses an older version of NTLM.

**Comment by clusby** [comment]
Cheers, I've sent an email to you with the messages. 

I'm not sure if the proxy supports v2. Is there a way (just witeshark?) To check for other traffic like in chrome?

**Comment by jborean93** [comment]
Thanks @clusby I'll try and get a look at this in the coming few days, sorry for the delay.

**Comment by jborean93** [comment]
I found some time this morning and here is some background on the flags sent in your example

Hex/Bits for Negotiate Flags
```
32 90 88 e2
00110010100100001000100011100010
```

Flags for Negotiate
```
NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY
NTLMSSP_NEGOTIATE_56
NTLMSSP_NEGOTIATE_OEM
NTLMSSP_NEGOTIATE_ALWAYS_SIGN
NTLMSSP_NEGOTIATE_SIGN
NTLMSSP_NEGOTIATE_128
NTLMSSP_NEGOTIATE_KEY_EXCH
NTLMSSP_NEGOTIATE_SEAL
NTLMSSP_NEGOTIATE_TARGET_INFO
NTLMSSP_NEGOTIATE_VERSION
NTLMSSP_NEGOTIATE_OEM_DOMAIN_SUPPLIED
```

Hex/Bits for Challenge Flags
```
32 82 08 e2
00110010100000100000100011100010
```

Flags for Challenge
```
NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY
NTLMSSP_NEGOTIATE_56
NTLMSSP_NEGOTIATE_OEM
NTLMSSP_NEGOTIATE_ALWAYS_SIGN
NTLMSSP_NEGOTIATE_SIGN
NTLMSSP_NEGOTIATE_128
NTLMSSP_NEGOTIATE_KEY_EXCH
NTLMSSP_NEGOTIATE_SEAL
NTLMSSP_NEGOTIATE_NTLM
NTLMSSP_NEGOTIATE_VERSION
```

The NTLMSSP_NEGOTIATE_VERSION is defined in MS-NLMP in 2.2.2.5

> T (1 bit): If set, requests the protocol version number. The data corresponding to this flag is provided
> in the Version field of the NEGOTIATE_MESSAGE, the CHALLENGE_MESSAGE, and the
> AUTHENTICATE_MESSAGE.<24> An alternate name for this field is
> NTLMSSP_NEGOTIATE_VERSION.

T is the seventh bit and in your examples are set in both the negotiate message sent to the server and the challenge message received from the server. This is why ntlm-auth is trying to parse the version as it is expecting it to be there when in fact it is not.

According to MS-NLMP in 2.2.1.2 under Version

> A VERSION structure (as defined in section 2.2.2.10) that SHOULD<9> be
> populated only when the NTLMSSP_NEGOTIATE_VERSION flag is set in the NegotiateFlags field.
> This structure is used for debugging purposes only. In normal (non-debugging) protocol
> messages, it is ignored and does not affect the NTLM message processing.

and further down in section 3.2.5.1.1

> If the NTLMSSP_NEGOTIATE_VERSION flag is set, the Version field MUST be set to the current
> version (section 2.2.2.10).

As this flag is set in the reply the server MUST HAVE set the version but in your case this did not happen. My thoughts are that the proxy you are using isn't conforming to the spec appropriately and it should have sent the version while it did not.

In the end it isn't critical for this field to be parsed so I've added a check beforehand to check the length and only retrieve it when the length > 48.

Are you able to try out this branch https://github.com/jborean93/ntlm-auth/tree/fix/challenge-versioning and let me know how it goes. If it works I'll merge it into master and create a new release for you.

**Comment by clusby** [comment]
Perfect - that does the trick for me thanks @jborean93 

I agree the proxy I'm going through is less than ideal. Many thanks for your project though.

**Comment by jborean93** [comment]
@clusby glad to hear that, I'll merge the changes into master and create a release soon.

**Comment by jborean93** [comment]
Hey @clusby I have made a release to pypi with these fixes in them https://pypi.python.org/pypi/ntlm-auth. Closing the issue as this should fix your issue.

**Comment by clusby** [comment]
Legend, thanks @jborean93
