### ISSUE TITLE
Missing copyright notice

### ISSUE THREAD

**Issue by jmdh** [jborean93/ntlm-auth#16]
I cannot find any copyright notice in this package, but I can see that multiple authors are involved due to the fork history on github. The LGPL license requires a clear copyright notice to be valid, as does the Debian project before I can package this (which is needed for requests-ntlm, which is needed for pywinrm, which is needed for ansible on windows, which I would like to see working in Debian).

Please could you include a copyright notice in somewhere obvious, like the PKG-INFO file? It's likely that all the past contributed would need to be listed, unless they were doing the work for hire.

Thanks!

**Comment by jborean93** [comment]
I'll have a look through, while this is based on a particular fork 90% of the code here is what I've written. I'll have a look at the stuff I forked and confirm the license is all correct.

Are you able to provide examples of what you are looking for, I'm not well versed in licensing and thought the LICENSE file, the `setup.py` listing would have been enough but obviously not.

**Comment by jmdh** [comment]
Odd, I didn't see your question in the email notification.

Anyway, thanks for looking at this. The setup.py contains information about (an) author but no copyright statement (a thing saying which legal entities own copyrights in the software. Actually, I see that pywinrm is no better in this regard, and it seems I missed that when packaging. It's more obvious for ntlm-auth because of the forking.

I'm not too familiar in how things are normally done in the python world, but here is an example of a copyright statement in a perl package that was maintained by different people at different times:

https://metacpan.org/source/DOM/Oxford-Calendar-2.11/lib/Oxford/Calendar.pm

It's worth noting that, in this example, the copyright holder is not necessarily the person contributing the code; for the time I was employed by the University my contributions were copyrighted by them. This explains why I can't assume that even code you are credited as writing is copyrighted by you.

If there is no copyright field in setup.py (and there doesn't seem to be from a quick google?!) then adding a section in README.md would be just as good.

**Comment by jborean93** [comment]
It seems like some python libraries I've looked at just now just add a copyright message in comments at the top.

**Comment by jmdh** [comment]
That would be ideal, thanks! (obviously as long as it's correct too :)

**Comment by jakirkham** [comment]
I think if you add a `MANIFEST.in` file in the top-level directory with the content below, this should fix the issue for the next release.

```
include LICENSE
```

**Comment by jakirkham** [comment]
cc @synapticarbors

**Comment by jborean93** [comment]
@jmdh @jakirkham I've just raised a PR that should resolve the issues you've noted here https://github.com/jborean93/ntlm-auth/pull/17. Are you able to check them and make sure they change what you are looking for and I will merge and create a release.

**Comment by jakirkham** [comment]
LGTM. Thanks for putting that together, @jborean93. :)
