### ISSUE TITLE
License Incompatibility

### ISSUE THREAD

**Issue by hlieberman** [jborean93/ntlm-auth#19]
Hello!

As part of packaging this for Debian, I found a license incompatibility (and a mismarking!).

The file `ntlm_auth/des_c.py`, `ntlm_auth/des.py`, and `ntlm_auth/des_data.py` are copyright Dmitry A. Rozmanov and licensed it as part of the NTLMAPS project under the GPLv2.  The header marking shows that it's LGPLv3+, which is incorrect.

Unfortunately, GPLv2 (aka GPLv2 only) isn't compatible with LGPLv3+.  If you hold the copyright to all other code, you could relicense the entire project under the LGPLv2.1+, which would effectively cause it to be distributed under GPLv2 itself.  The other option would be removing those files from the project and replacing them.

Please let me know.

**Comment by jborean93** [comment]
I'll have to look into it, the code was was based on another library and obviously I didn't do my due diligence so thanks for bringing it to my attention.

AFAIC the rest of the code was written by myself and so I can re-license it but I need to look into it and see what my full options are.

Thanks

Jordan

**Comment by jborean93** [comment]
The des code was removed and rewritten by myself in this commit https://github.com/jborean93/ntlm-auth/pull/20. It also makes a few other changes and also changed the license from GPL to MIT now the code is either written by myself or approved by other contributors.
