### ISSUE TITLE
NTLM authentication fails because MD4 and MD5 are not available

### ISSUE THREAD

**Issue by bergerod** [jborean93/ntlm-auth#22]
When using ntlm_auth and hash md4 and md5 are not available the code fails.  We can no longer use md4 and md5 due to security concerns.  Is there are work around or update to use sha1?  

We are receiving unsupported hash types when executing the code.  
ValueError: unsupported hash type md4

**Comment by jborean93** [comment]
Unfortunately there is nothing I can do to help you with this issue. The ntlm spec required md4/md5 to be used as part of calculating the hash and we can't change the spec. In reality NTLM is a really old protocol that you honestly shouldn't be using if possible, when you are in a domain environment then take the time to start using Kerberos.
