### ISSUE TITLE
example doesn't work properly

### ISSUE THREAD

**Issue by carlosjordao** [jborean93/ntlm-auth#29]
hi!
The example provided doesn't work out-of-box. It gives a error on this line:

challenge_message = http.response.headers['HEADERFIELD']

**Comment by jborean93** [comment]
The examples are mostly just psuedo code and require a lot of other things to be in place. In any case this module is effectively EOL and I high recommend you use [pyspnego](https://github.com/jborean93/pyspnego) instead which includes NTLM auth support but also Kerberos if you have the required libraries installed.
