### ISSUE TITLE
Generating md4 hash fails

### ISSUE THREAD

**Issue by ekooiker** [jborean93/ntlm-auth#31]
After upgrading openssl on my OS, generating a md4 hash doesn't work anymore and I get the following error:
```
Traceback (most recent call last):
  File "/home/erik/projects/exchange/.venv/lib/python3.10/site-packages/ntlm_auth/compute_hash.py", line 66, in _ntowfv1
    digest = hashlib.new('md4', password.encode('utf-16-le')).digest()
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md4
```

I found a solution [here](https://github.com/cannatag/ldap3/commit/6c13304f03a7f66df40a43eccbe49ff75c2d6099)
Would you be interested in a PR?

**Comment by jborean93** [comment]
As per the README this library is essentially deprecated in favour of [pyspnego](https://github.com/jborean93/pyspnego) where future development is done. It has solved this problem by implementing an MD4 hasing function itself. I've got no plans on updating this library and anybody that uses it should consider moving across to `pyspnego` or some other library.

**Comment by eusoubrasileiro** [comment]
@jborean93 is there any examples on how to use like `HttpNtlmAuth` in your new package. Didn't find anything there on those examples.
