### ISSUE TITLE
Can this library compute Type 2 and the final authentication result messages?

### ISSUE THREAD

**Issue by MediumOne** [jborean93/ntlm-auth#5]
I am working on creating a server side NTLM authentication component that will help in testing of NTLM clients. Since this server side component is only meant for testing purposes, it will not integrate with Active Directory or Domain Controller, but will simply authenticate using a hard-coded list of credentials. However, it will support all types of NTLM authentication - LM, NTLM, LMv2, NTLMv2, NTLM2 Session Response, NTLM1 Signing & Sealing, etc. This will provide a way to test the NTLM capabilities of the clients. It will be an NTLM equivalent to http://httpbin.org/basic-auth/user/passwd which can be used to test basic authentication.

My question is - does this library have - (1) support to compute Type 2 (Challenge) messages by taking a Type 1 message as input and (2) support to compute the authentication result message by taking a Type 3 message? Or is this only a client-side library that will help in generating Type 1 and Type 3 messages?

I took a look at the code and I think this library only helps to compute Type 1 and Type 3 messages. But can you please confirm? (I am new to Python and I might have missed something.)

**Comment by jborean93** [comment]
Hi

This library only supports client side authentication with no functionality to compute Type 2 and verify Type 3 messages. There's nothing stopping you from raising a pull request with the functionality required as the basics are already there.

Thanks

Jordan

**Comment by MediumOne** [comment]
Sure, will give it a try. Thanks.

Closing issue.
