### ISSUE TITLE
unable to use Python3 with NTLM

### ISSUE THREAD

**Issue by blshkv** [jborean93/ntlm-auth#6]
setup.py requires:
```install_requires=[ 'six', 'ordereddict' ],```
However, ordereddict does not support python3. See the following for more details:
https://pypi.python.org/pypi/ordereddict

Please test python3 and fix the requirement.

**Comment by jborean93** [comment]
Ordereddict is only used with python 2.6 as it doesn't have it natively built in, later versions use the builtin version instead. Are you getting a specific error as this works in Python 3 for me?

**Comment by blshkv** [comment]
I'm creating a package for Pentoo Linux and follow strict dependency list. It looks like that is safe to drop this requirement with Python3.

**Comment by jborean93** [comment]
Is the common practice to use an if statement in the setup.py and add it only if the version is 2.6? Sorry Python isn't my default language and I am not 100% sure what people do in this situation.

**Comment by blshkv** [comment]
I just found an example here:
https://github.com/pecan/pecan/blob/master/setup.py

**Comment by jborean93** [comment]
Thanks I'll get around to updating hopefully tomorrow.

**Comment by blshkv** [comment]
This one looks better:
https://hynek.me/articles/conditional-python-dependencies/
```
install_requires=[
        # ...
        "monotonic ; python_version<'3.3'",
    ]
```

**Comment by jborean93** [comment]
Hey @blshkv I've created a new release at 1.0.3 where ordereddict is only installed if the inbuild Python isn't available. I tried using the 2 examples but it caused a few issues with the CI tools as the setuptools version was too old to handle it.

**Comment by blshkv** [comment]
ok, ordereddict package is no longer listed at https://pypi.python.org/pypi/ntlm-auth in the "Requires Distributions". It may be a bad thing because it became a hidden dependency. 

I would rather require a newer version of setuptools if it solves the problem.

**Comment by blshkv** [comment]
found an another way (using additional py26-requirements.txt):
https://nicolaiarocci.com/ordered-dictionaries-with-python-2-4-2-6/
https://github.com/pyeve/eve/commit/ae292f42a6ea92a447b194aaf17d8447b859b0ab

**Comment by blshkv** [comment]
Just for the records, here is the official documentation:
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

**Comment by jborean93** [comment]
I've made the latest changes to use the PEP508 environment markers and have uploaded that as version 1.0.4. Hopefully this works with what you need.

**Comment by jborean93** [comment]
Closing as the environment markers have been set.

**Comment by blshkv** [comment]
Thank you!
